AWSTemplateFormatVersion: 2010-09-09
Description: Security Group Template
Metadata: 
  Author: !Ref ParamAuthor
Parameters: 
  ParamAuthor:
    Type: String
    Description: Security Group Templated Created by Bankole Peters

  AllowedSSHCidrRangeParam:
    Description: The IP address range that can be used to ssh to the EC2Instance
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

  SecurityGroupPorts:
    Description: Simple Description of a Number Parameter, with MinValue and MaxValue
    Type: Number
    AllowedValues: 
      - 80
      - 443
      - 22 

Resources: 
  SecurityGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for VPC and SSH
      GroupName: Transact-VPC-SG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref SecurityGroupPorts
          ToPort: !Ref SecurityGroupPorts
          CidrIp: !Ref AllowedSSHCidrRangeParam

Outputs:
  SecurityGrpOutputName: 
    Description: Name of EC2 Instance Security Group
    Value: !Ref SecurityGrp

  SecurityGroupId:
    Description: ID output of Transact-VPC Security Group
    Value: !GetAtt
        - SecurityGrp
        - GroupId
    Export:
      Name: Server-Security-GroupId

  VpcId:
    Description: VPC Id the security group will be located in.
    Value: !GetAtt
      - SecurityGrp
      - VpcId
